"""initial schema

Revision ID: 0d8cf70cf19a
Revises: 
Create Date: 2026-07-23 11:20:57.175556
"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0d8cf70cf19a'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('markets',
    sa.Column('condition_id', sa.String(length=80), nullable=False),
    sa.Column('question', sa.String(length=512), nullable=False),
    sa.Column('slug', sa.String(length=256), nullable=True),
    sa.Column('category', sa.String(length=128), nullable=True),
    sa.Column('outcomes', sa.JSON(), nullable=False),
    sa.Column('clob_token_ids', sa.JSON(), nullable=False),
    sa.Column('outcome_prices', sa.JSON(), nullable=False),
    sa.Column('volume', sa.Float(), nullable=False),
    sa.Column('liquidity', sa.Float(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('closed', sa.Boolean(), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('condition_id')
    )
    op.create_index(op.f('ix_markets_active'), 'markets', ['active'], unique=False)
    op.create_index(op.f('ix_markets_category'), 'markets', ['category'], unique=False)
    op.create_index(op.f('ix_markets_slug'), 'markets', ['slug'], unique=False)
    op.create_index(op.f('ix_markets_volume'), 'markets', ['volume'], unique=False)
    op.create_table('traders',
    sa.Column('proxy_wallet', sa.String(length=64), nullable=False),
    sa.Column('username', sa.String(length=128), nullable=True),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('total_pnl', sa.Float(), nullable=False),
    sa.Column('total_volume', sa.Float(), nullable=False),
    sa.Column('position_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('proxy_wallet')
    )
    op.create_table('recommendations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('condition_id', sa.String(length=80), nullable=False),
    sa.Column('outcome', sa.String(length=64), nullable=False),
    sa.Column('asset', sa.String(length=80), nullable=True),
    sa.Column('direction', sa.String(length=8), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('consensus_size_usd', sa.Float(), nullable=False),
    sa.Column('supporter_count', sa.Integer(), nullable=False),
    sa.Column('avg_entry_price', sa.Float(), nullable=False),
    sa.Column('current_price', sa.Float(), nullable=False),
    sa.Column('rationale', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['condition_id'], ['markets.condition_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendations_condition_id'), 'recommendations', ['condition_id'], unique=False)
    op.create_index(op.f('ix_recommendations_status'), 'recommendations', ['status'], unique=False)
    op.create_index('ix_recs_confidence', 'recommendations', ['confidence'], unique=False)
    op.create_index('ix_recs_market', 'recommendations', ['condition_id'], unique=False)
    op.create_table('trader_positions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('proxy_wallet', sa.String(length=64), nullable=False),
    sa.Column('condition_id', sa.String(length=80), nullable=True),
    sa.Column('asset', sa.String(length=80), nullable=False),
    sa.Column('outcome', sa.String(length=64), nullable=True),
    sa.Column('size', sa.Float(), nullable=False),
    sa.Column('avg_price', sa.Float(), nullable=False),
    sa.Column('cur_price', sa.Float(), nullable=False),
    sa.Column('initial_value', sa.Float(), nullable=False),
    sa.Column('current_value', sa.Float(), nullable=False),
    sa.Column('cash_pnl', sa.Float(), nullable=False),
    sa.Column('percent_pnl', sa.Float(), nullable=False),
    sa.Column('realized_pnl', sa.Float(), nullable=False),
    sa.Column('redeemable', sa.Boolean(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['condition_id'], ['markets.condition_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['proxy_wallet'], ['traders.proxy_wallet'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('proxy_wallet', 'asset', name='uq_position')
    )
    op.create_index('ix_positions_market', 'trader_positions', ['condition_id'], unique=False)
    op.create_index(op.f('ix_trader_positions_proxy_wallet'), 'trader_positions', ['proxy_wallet'], unique=False)
    op.create_table('trader_scores',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('proxy_wallet', sa.String(length=64), nullable=False),
    sa.Column('window', sa.String(length=16), nullable=False),
    sa.Column('profitability', sa.Float(), nullable=False),
    sa.Column('consistency', sa.Float(), nullable=False),
    sa.Column('sizing', sa.Float(), nullable=False),
    sa.Column('risk_adjusted', sa.Float(), nullable=False),
    sa.Column('composite', sa.Float(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['proxy_wallet'], ['traders.proxy_wallet'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('proxy_wallet', 'window', name='uq_score_window')
    )
    op.create_index('ix_scores_composite', 'trader_scores', ['window', 'composite'], unique=False)
    op.create_index(op.f('ix_trader_scores_composite'), 'trader_scores', ['composite'], unique=False)
    op.create_index(op.f('ix_trader_scores_proxy_wallet'), 'trader_scores', ['proxy_wallet'], unique=False)
    op.create_table('trades',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('condition_id', sa.String(length=80), nullable=False),
    sa.Column('tx_hash', sa.String(length=80), nullable=True),
    sa.Column('wallet', sa.String(length=64), nullable=False),
    sa.Column('asset', sa.String(length=80), nullable=True),
    sa.Column('outcome', sa.String(length=64), nullable=True),
    sa.Column('side', sa.String(length=8), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('size', sa.Float(), nullable=False),
    sa.Column('usd_value', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['condition_id'], ['markets.condition_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tx_hash', 'wallet', 'asset', name='uq_trade_dedupe')
    )
    op.create_index(op.f('ix_trades_condition_id'), 'trades', ['condition_id'], unique=False)
    op.create_index('ix_trades_market_ts', 'trades', ['condition_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_trades_wallet'), 'trades', ['wallet'], unique=False)
    op.create_index('ix_trades_wallet_ts', 'trades', ['wallet', 'timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_trades_wallet_ts', table_name='trades')
    op.drop_index(op.f('ix_trades_wallet'), table_name='trades')
    op.drop_index('ix_trades_market_ts', table_name='trades')
    op.drop_index(op.f('ix_trades_condition_id'), table_name='trades')
    op.drop_table('trades')
    op.drop_index(op.f('ix_trader_scores_proxy_wallet'), table_name='trader_scores')
    op.drop_index(op.f('ix_trader_scores_composite'), table_name='trader_scores')
    op.drop_index('ix_scores_composite', table_name='trader_scores')
    op.drop_table('trader_scores')
    op.drop_index(op.f('ix_trader_positions_proxy_wallet'), table_name='trader_positions')
    op.drop_index('ix_positions_market', table_name='trader_positions')
    op.drop_table('trader_positions')
    op.drop_index('ix_recs_market', table_name='recommendations')
    op.drop_index('ix_recs_confidence', table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_status'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_condition_id'), table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_table('traders')
    op.drop_index(op.f('ix_markets_volume'), table_name='markets')
    op.drop_index(op.f('ix_markets_slug'), table_name='markets')
    op.drop_index(op.f('ix_markets_category'), table_name='markets')
    op.drop_index(op.f('ix_markets_active'), table_name='markets')
    op.drop_table('markets')
    # ### end Alembic commands ###
