"""add orders table

Revision ID: b1680a0e261a
Revises: 0d8cf70cf19a
Create Date: 2026-07-23 11:44:30.958702
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1680a0e261a'
down_revision: Union[str, None] = '0d8cf70cf19a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('condition_id', sa.String(length=80), nullable=True),
    sa.Column('recommendation_id', sa.Integer(), nullable=True),
    sa.Column('asset', sa.String(length=80), nullable=False),
    sa.Column('outcome', sa.String(length=64), nullable=True),
    sa.Column('side', sa.String(length=8), nullable=False),
    sa.Column('mode', sa.String(length=8), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('size_usd', sa.Float(), nullable=False),
    sa.Column('size_shares', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('external_id', sa.String(length=120), nullable=True),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['condition_id'], ['markets.condition_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_orders_created', 'orders', ['created_at'], unique=False)
    op.create_index(op.f('ix_orders_mode'), 'orders', ['mode'], unique=False)
    op.create_index(op.f('ix_orders_status'), 'orders', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orders_status'), table_name='orders')
    op.drop_index(op.f('ix_orders_mode'), table_name='orders')
    op.drop_index('ix_orders_created', table_name='orders')
    op.drop_table('orders')
    # ### end Alembic commands ###
