"""add order pnl

Revision ID: ff72bf6eb51c
Revises: b1680a0e261a
Create Date: 2026-07-23 12:09:29.803365
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff72bf6eb51c'
down_revision: Union[str, None] = 'b1680a0e261a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('pnl', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'pnl')
    # ### end Alembic commands ###
